versionize/versionize

README.md, Versionize.Tests/WorkingCopyTests.cs, Versionize/Program.cs, Versionize/VersionIncrement.cs, Versionize/WorkingCopy.cs
This parameter allows for users to specify that Versionize should ignore insignificant commits.
Insignificant commits are any non- `feat`, `fix` or `BREAKING` commit
fixes #7
=> feat: Added parameter to ignore insignificant commits

Versionize/RepositoryExtensions.cs, Versionize/WorkingCopy.cs
Fixed typo in method name.
Changed from `GteCommitsSinceLastVersion` to `GetCommitsSinceLastVersion`
=> fix: typo in method name

Versionize.Tests/WorkingCopyTests.cs, Versionize/Program.cs, Versionize/WorkingCopy.cs
Adds an `--commit-suffix` option to be able to add a suffix to the release commit message created when running `versionize`.
This is useful when running `versionize` in a CI/CD pipeline that triggers on each push to a target branch; usually `main` or `master`. 
By adding the suffix `[skip ci]` to the release commit message we prevent the pipeline from re-triggering when pushing back the CHANGELOG.md, tag and updated `.csproj`-files.
Sample usage
```
// Running
versionize --commit-suffix [skip ci]
// would result in following commit message
chore(release): 1.2.0 [skip ci]
```
=> feat: add release commit message suffix option

Versionize.Tests/Changelog/ChangelogBuilderTests.cs, Versionize/Changelog/ChangelogBuilder.cs
Occurs when file is generated for the first time. Just had to remove the verbatim marker.
=> fix: changelog includes literal line break characters

Versionize.Tests/Changelog/AzureLinkBuilderTests.cs, Versionize.Tests/Changelog/GithubLinkBuilderTests.cs, Versionize/Changelog/AzureLinkBuilder.cs, Versionize/Changelog/GithubLinkBuilder.cs
Occurs when .git suffix is not included.
It's just a naming convention, so it's not required.
Fixes #30
Fixes #34
=> fix: invalid url exception

README.md, Versionize.Tests/Changelog/ChangelogBuilderTests.cs, Versionize.Tests/Versionize.Tests.csproj, Versionize/Changelog/ChangelogBuilder.cs, Versionize/ChangelogOptions.cs, Versionize/ChangelogSection.cs, Versionize/ConfigurationContract.cs, Versionize/Program.cs, Versionize/Versionize.csproj, Versionize/VersionizeOptions.cs, Versionize/WorkingCopy.cs
Hello @saintedlama! Love the library.
I thought it would be cool to support customizing the changelog sections and header (via the `.versionize` file) like standard-version does with `.versionrc`. I'd still like to add some more tests and do another code overview, but I figured I'd go ahead and create an "in progress" PR in order to get your thoughts.
So the `.versionize` json would look something like this:
```json
{
"skipDirty": true,
"changelog": {
"header": "My changelog",
"sections": [
{
"type": "feat",
"section": "Cool Features",
"hidden": false
}
]
}
}
```
=> feat: support changelog customization options

Versionize.Tests/Changelog/ChangelogBuilderTests.cs, Versionize.Tests/TestSupport/ChangelogStringBuilder.cs, Versionize.Tests/WorkingCopyTests.cs, Versionize/Changelog/ChangelogBuilder.cs, Versionize/ChangelogOptions.cs, Versionize/WorkingCopy.cs
Output looks like the following:
_Side note: Not sure what's wrong with the coloring on my machine._
=> feat: print changelog diff during a dry-run

README.md, Versionize.Tests/VersionIncrementStrategyTests.cs, Versionize.Tests/WorkingCopyTests.cs, Versionize/ConfigurationContract.cs, Versionize/Program.cs, Versionize/VersionIncrementStrategy.cs, Versionize/Versioning/InvalidPrereleaseIdentifierException.cs, Versionize/Versioning/PrereleaseIdentifier.cs, Versionize/Versioning/SemanticVersionExtensions.cs, Versionize/VersionizeOptions.cs, Versionize/WorkingCopy.cs
A non-non-elegant but working solution
=> feat: support pre-releases 

README.md, Versionize.Tests/WorkingCopyTests.cs, Versionize/Program.cs, Versionize/VersionizeOptions.cs, Versionize/WorkingCopy.cs
resolves #74 
Still need to add tests and update the README but seems to work pretty well when trying out dummy version bumps on the Versionize repository locally.
=> feat: add support for aggregating prereleases in changelog

Versionize.Tests/WorkingCopyTests.cs, Versionize/WorkingCopy.cs
simple fix to Issue #78 
Note: for some Reason the `projects.version` property is changed by `WriteVersion` altough the projects objects are not reloaded, therefore I am not sure if this is sufficient or if there is an underlying issue
=> fix: moved bump statement up before csproj are altered Issue #78 

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, Versionize.Tests/Versionize.Tests.csproj, Versionize/Versionize.csproj
I guess we should also eventually decide if we want to follow the [dotnet release lifecycle](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core) e.g. removing net5 support for example since the end date was May 2022.
=> feat: add net7 support

Versionize/WorkingCopy.cs
Fix for issue: #89
The changes in this commit, makes the "--workingDir" argument work as expected.
This means, that only projects in the specified working directory will be versionized.
Example: "Solution with 2 projects (A, B) located in a src folder"
- Versionize is run from 'src' folder with no --workingDir argument set
- Both projects gets versionized (if no inconsistent versioning)
- Versionize is run from 'src' folder but with --workingDir argument set to './A'
- Only project A gets versionized (ignoring inconsistent versioning)
- This of course also works for project B
=> fix: Preserve 'workingDirectory' set in args while still resolving directory of '.git' folder

Versionize/Project.cs
In the case of checking whether a project can be versioned, the invalid operation exception is swallowed because it is not really invalid for that use case.  This update only builds the exception for the Create case and so skips the cost of the exception in the more common case
For addional context, I have a legacy WPF application with dozens of libraries that can't be converted to SDK format and so throw this exception a lot during the versioning process.  This change cuts about 10s off the runtime of the versonize process.
=> fix: improve performance by not throwing exceptions

README.md, Versionize.Tests/ProgramTests.cs, Versionize/Program.cs, Versionize/Properties/launchSettings.json
I took a stab at adding the configuration command line option.
If it's not passed in then it'll default to the cwd variable.
The README and other documentation hasn't been updated.
=> feat: added config file command line option

README.md
Include an explanation of how the .versionize file is deserialized behind the scenes.
This will enhance understanding
of how to properly structure and write the
configuration file.
=> docs: explain how .versionize deserialized

Versionize.Tests/WorkingCopyTests.cs, Versionize/Config/CliConfig.cs, Versionize/Config/ConfigProvider.cs, Versionize/Config/FileConfig.cs, Versionize/Config/VersionizeOptions.cs, Versionize/Git/RepositoryExtensions.cs, Versionize/Lifecycle/ConventionalCommitProvider.cs
- Add first-parent-commits options : The first parent only options allows you to ignore commits that are not the first parent.
See #139 
Work based on version 2 - See #135
=> feat: Add first-parent commits option

README.md, Versionize.Tests/WorkingCopyTests.cs, Versionize/Config/CliConfig.cs, Versionize/Config/ConfigProvider.cs, Versionize/Config/FileConfig.cs, Versionize/Config/VersionizeOptions.cs, Versionize/Lifecycle/ConventionalCommitProvider.cs
@RemiCELLARD  Sorry, I missed this in the PR review. I'd like to keep the cli and file option names the same to minimize confusion. Trying to obey the following documentation snippet as closely as possible _(unfortunately there are already a few that don't match, so I guess we can consider those in the next major release)_.
> Any of the command line parameters accepted by versionize can be provided via configuration file leaving out any -. For example skip-dirty can be provided as skipDirty in the configuration file.
**Before**
```
--first-parent-commits
FirstParentOnlyCommit
```
**After**
```
--first-parent-only-commits
FirstParentOnlyCommits
```
This is technically a breaking change but v2 was released less than 24 hours ago and this is a brand new command, so I'm fine with bending the …
=> feat: modify "first parent only" option names to match

README.md
Remove changelogAll option and instead using
includeAllCommits based on ChangelogOptions.cs
=> docs: update to includeAllCommits option

Versionize.Tests/Config/ConfigProviderTests.cs, Versionize/Config/ConfigProvider.cs
#146
Detect duplicate changelog paths during config read. 
Inform the user and exit with an error message.
@cabauman Please review especially the tests.
=> fix: address #146

Versionize.Tests/Git/RepositoryExtensionsTests.cs, Versionize/Git/RepositoryExtensions.cs
Also remove useless tests that are testing library code instead of our own.
=> fix: version bump fails when tag-only and a prerelease exists

README.md
Description
This PR addresses [#155](https://github.com/versionize/versionize/issues/155) by updating the README to include a section on configuring custom commit header patterns. While this feature is already supported, it was not documented clearly, leading to potential confusion for users.
- Added a "Custom Commit Header Patterns" section to the README.
- Included a JSON example configuration that demonstrates how to set up custom patterns.
- Provided examples of commit messages that would be matched by the custom patterns.
This change ensures that users do not have to look into test files to discover this functionality.
=> docs: clarify custom commit header patterns in README

Versionize.Tests/Changelog/AzureLinkBuilderTests.cs, Versionize/Changelog/AzureLinkBuilder.cs
The pull request fixes the urls build for the changelog using Azure, urls included company multiple times /_git/ for work items.
These 2 parts of the url made it so that the links don't work.
=> fix: Changed regex for azure commits and issues to be in line with the current azure environment

Versionize.Tests/ConventionalCommits/ConventionalCommitParserTests.cs, Versionize/Config/CommitParserOptions.cs, Versionize/ConventionalCommits/ConventionalCommitParser.cs
Adds support for JIRA issues within commits via a new _CommitParserOptions_ `IssuesPatterns` property, used to extend the default issues pattern.
Usage:
```json
{
"CommitParser": {
"IssuesPatterns": [
"(?<issueToken>(?<issueId>[A-Z]+\\-\\d+))"
]
}
}
```
With this, commit messages like the following:
> fix: subject text. (NC-64)
will correctly identify JIRA issue **NC-64**
Remaining hooks into JIRA would then be dependent on configuration of _chagnelog/linkTemplates/issueLink_ to resolve to the specific JIRA issue URL.
=> feat: add support for JIRA issues

Versionize.Tests/WorkingCopyTests.cs, Versionize/Config/VersionizeOptions.cs, Versionize/WorkingCopy.cs
fixes "--skip-commit --skip-tag" still enforces Git config Fixes #167
=> feat: add Git configuration checks for versioning operations
